colorScheme = "avocado"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
mainSections = [ "posts" ]
disableImageOptimization = true
disableTextInHeader = true
defaultBackgroundImage = "img/cube.jpg"
defaultFeaturedImage = "img/logo.jpg"
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = false
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "img/cube.jpg"
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true

[article]
showDate = false
showViews = true
showLikes = true
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = false
showEdit = false
editAppendPath = false
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 3
showTaxonomies = true
showAuthorsBadges = true
showSummary = false
showWordCount = false
showZenMode = ""

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyD8RsKtADMLK0kV0Jz-8cw2aVRoOL8IZhI"
authDomain = "github-2beb6.firebaseapp.com"
projectId = "github-2beb6"
storageBucket = "github-2beb6.appspot.com"
messagingSenderId = "835651949614"
appId = "1:835651949614:web:91a5a2efeb3e0299ffbbbf"
measurementId = "G-Y15Y2DTYDX"

[fathomAnalytics]

[buymeacoffee]

[verification]

[posthog]
apiKey         = "phc_jtawtHjdZmzvIJ5djMdTOz6GrhwYU3WxJAmxkZG8V8l"
apiHost        = "https://us.i.posthog.com"
defaults       = "2025-05-24"
person_profiles = "identified_only"
